"""Initial migration.

Revision ID: c122f630287b
Revises: 
Create Date: 2025-07-23 20:09:48.178243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c122f630287b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('metode', sa.String(length=100), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kebutuhan_koleksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_perpustakaan', sa.String(length=100), nullable=False),
    sa.Column('subjek', sa.String(length=100), nullable=False),
    sa.Column('jumlah_buku', sa.Integer(), nullable=False),
    sa.Column('prioritas', sa.String(length=20), nullable=False),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('tanggal_pengajuan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perpus_desa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('desa', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_perpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('perpus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bukti_pengiriman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donasi_id', sa.Integer(), nullable=False),
    sa.Column('bukti_resi', sa.String(length=255), nullable=True),
    sa.Column('tanggal_pengiriman', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['donasi_id'], ['donasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donasi_id', sa.Integer(), nullable=False),
    sa.Column('subjek_buku', sa.String(length=100), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donasi_id'], ['donasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_donasi')
    op.drop_table('bukti_pengiriman')
    op.drop_table('admin_perpus')
    op.drop_table('user')
    op.drop_table('perpus_desa')
    op.drop_table('kunjungan')
    op.drop_table('kebutuhan_koleksi')
    op.drop_table('donasi')
    # ### end Alembic commands ###
